version: '3.1'
services:

  service:
    image: product
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3004
      - NODE_ENV=development
      - ENV=dev
      - DATABASE_HOST=dev-db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=product
      - DATABASE_SCHEMA=public
      - DATABASE_SYNCHRONIZE=false
      - DATABASE_POOL_SIZE=10
      - KAFKA_DEFAULT_BROKER_URL=kafka:9092
      - KAFKA_DEFAULT_CLIENT_ID=template-service
      - KAFKA_DEFAULT_GROUP_ID=template-service-dev
      - KAFKA_DEFAULT_AUTO_CREATE_TOPIC=true
      - KAFKA_DEFAULT_REQUEST_TIMEOUT=60000
      - KAFKA_DEFAULT_CONCURRENTLY=4
      - KAFKA_DEFAULT_SSL=false
      - KAFKA_DEFAULT_MECHANISM=NONE
      - KAFKA_DEFAULT_USERNAME=dummy
      - KAFKA_DEFAULT_PASSWORD=dummy
    ports:
      - 54319:3004
    depends_on:
        - zookeeper
        - kafka

  dev-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: product
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 54323:8080

  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    restart: unless-stopped
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    restart: unless-stopped
    ports:
      - 9092
      - 9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka-admin:
      image: 'docker.redpanda.com/vectorized/console:latest'
      restart: unless-stopped
      ports:
        - 54324:8080
      environment:
        - KAFKA_BROKERS=kafka:9092
      depends_on:
        - zookeeper
        - kafka