name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t asia-southeast1-docker.pkg.dev/sinuous-axiom-390804/assignment-order/assignment-order:${{ github.sha }} .

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker Client of Gcloud
      run:  |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push asia-southeast1-docker.pkg.dev/sinuous-axiom-390804/assignment-order/assignment-order:${{ github.sha }}

    - name: Checkout Config Repo
      uses: actions/checkout@v4
      with:
        repository: lenguyenhungthinh/assignment-config-service
        ref: main
        token: ${{ secrets.PAT_TOKEN }}

    - name: Config Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Setup kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Update the image
      run: |
        GCP_IMAGE_NAME="asia-southeast1-docker.pkg.dev/sinuous-axiom-390804/assignment-order/assignment-order:${{ github.sha }}"
        REPO_PATH="apps/order-service/overlays/dev"
        cd ${REPO_PATH}
        kustomize edit set image order-service=${GCP_IMAGE_NAME}
        git add .
        git commit -m "Update image tag to `${{ github.sha }}`"
        git push
